name: Application Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Run linting
        run: npm run lint
        working-directory: frontend

      - name: Run tests
        run: npm test
        working-directory: frontend

      - name: Build Next.js app
        run: npm run build
        working-directory: frontend
